# Generated by Django 4.2 on 2023-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
