# Generated by Django 4.2 on 2023-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=255, verbose_name='Тип'),
        ),
    ]
